	FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1
ENV RECORDS_DIR=/records
ENV WHISPER_MODEL=large-v3
ENV WHISPER_LANGUAGE=pt
ENV WHISPER_DEVICE=cpu
ENV WHISPER_COMPUTE_TYPE=int8
ENV CALL_BACKEND_UPLOAD_URL=http://192.168.0.36:8789/api/call/recordings
ENV GATEWAY_SECRET=72c9e06fb13682bb94b025a9f8053a7874acf532
ENV KEEP_LOCAL_FILES=false
ENV UPLOAD_TIMEOUT_SECONDS=120
ENV TRANSCRIBE_MIXED_AUDIO=false

RUN apt-get update && apt-get install -y \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir faster-whisper watchdog requests

WORKDIR /app

COPY transcribe_watch.py /app/transcribe_watch.py

CMD ["python", "/app/transcribe_watch.py"]
